package com.nalexand.swingy.ui.gui.forms;

import com.nalexand.swingy.model.Hero;
import com.nalexand.swingy.model.ModelFacade;
import com.nalexand.swingy.ui.Command;

import javax.swing.*;
import java.awt.*;
import java.util.List;

public class CreateHeroForm {
    private JButton createHeroButton;
    private JPanel panel1;

    public CreateHeroForm(ModelFacade modelFacade) {
        $$$setupUI$$$();
        List<Hero> createdHeroes = modelFacade.getCreatedHeroes();
        for (Hero hero : createdHeroes) {
            addSelectHeroButton(hero);
        }
        createHeroButton.addActionListener(e -> modelFacade.resolveCommand(Command.KEY_1));
    }

    public JPanel getPanel1() {
        return panel1;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        createHeroButton = new JButton();
        createHeroButton.setText("Create hero");
        panel1.add(createHeroButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void addSelectHeroButton(Hero hero) {

    }
}
