package com.nalexand.swingy.ui.gui.forms;

import com.nalexand.swingy.controller.GameProcessController;
import com.nalexand.swingy.model.ModelFacade;
import com.nalexand.swingy.ui.gui.KeyListenerForm;
import com.nalexand.swingy.ui.gui.custom.WorldMapPanel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;

public class WorldMapForm extends KeyListenerForm {

    private JPanel worldMap;

    public WorldMapForm(ModelFacade model, GameProcessController controller) {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();

        listenKey(KeyEvent.VK_W, () -> controller.moveHero(0, -1));
        listenKey(KeyEvent.VK_A, () -> controller.moveHero(-1, 0));
        listenKey(KeyEvent.VK_S, () -> controller.moveHero(0, 1));
        listenKey(KeyEvent.VK_D, () -> controller.moveHero(1, 0));
        listenKey(KeyEvent.VK_U, controller::unstuck);

        WorldMapPanel worldMapPanel = new WorldMapPanel(model);
        worldMapPanel.setLayout(new GridBagLayout());
        worldMap.add(worldMapPanel, BorderLayout.CENTER);
        //endregion
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        worldMap = new JPanel();
        worldMap.setLayout(new BorderLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return worldMap;
    }

    @Override
    public JComponent getRootComponent() {
        return worldMap;
    }
}
